### ISSUE TITLE
Not able to log in

### ISSUE THREAD

**Issue by LiamPower02** [eni9889/SC-PP-ISSUES#10]
I was going to be off of my phone for a little while, so I asked one of my friends to keep my streaks for me and they used my log in on their phone which does not have Snap +. After I returned, I wasn't able to log in because of a connectivity issue. I uninstalled the tweak and was able to log in and use Snapchat perfectly fine. After reinstalling it and doing this multiple times, it still hasn't worked. I am on iOS 10.2 and the latest version of Snap+ and Snapchat.

**Comment by Byakou** [comment]
Just happened to me today too, this is really bad please fix.

**Comment by TheNightRider12** [comment]
Unlim has said that he has no intention of adding DRM bypass into the tweak. He has no time to do that with his full time job.

**Comment by noclueforreal** [comment]
It says the same on my Snap; "Connection not possible" and on the Page it says it coud be 'because the plugin, a fix woud be godly
