### ISSUE TITLE
"Could not refresh. Please try again" on SC++

### ISSUE THREAD

**Issue by becazieg** [eni9889/SC-PP-ISSUES#100]
I have the last version on Snapchat++ sideloaded. As soon as I open the app, it says "Could not refresh. Please try again." It doesn't even try to load, it says that immediately. None of my stories are loading, I can only see the featured and shows stories. Gr8. This whole thing is making the tweak useless.
This error is on both SC++ installed with cydia impactor, and the one available on the Tutu app.
Please fix this.
Tweak version: 1.6r-169
Snapchat version: 10.19.5.0

**Comment by nassou66** [comment]
i have the same problem, anyone can help please?

**Comment by sololau00** [comment]
use this to install snapchat++ https://appvalley.vip
