### ISSUE TITLE
Auto-Save Incoming Snaps Behavior Change

### ISSUE THREAD

**Issue by uhhmaybe** [eni9889/SC-PP-ISSUES#105]
I've just installed the sideloaded version of `171` [from @JMccormick264's repo](https://github.com/JMccormick264/SnapPP/releases/tag/Tweak_1.6r-171), and the behavior of the auto-save incoming snaps feature seems to not be working right.  Neither pictures nor videos are saving until I actually open them, as opposed to auto-saving as soon as they load.

Also, even though I have notifications enabled, I only get notifications for saving an outgoing snap, and no notifications for incoming snaps.  I think this is probably because they're not saving until they're viewed, at which point I wouldn't be able to see the notification banner anyway.

Previously I was on `168` which is before the change in `170` for "fix autosave of incoming media", so the problem might be in `170` as well.

`iPhone 7 Plus`
`iOS 10.3.3`
`Snapchat++ v10.20.0 v1.6r-171`
`Sideloaded via Cydia Impactor`

Let me know if I can provide any more info, or screen shots.

Side note: I also get the Could Not Refresh error with Stories using `170` that other users are reporting, but not with the old `168` sideloaded version [located here](https://github.com/JMccormick264/SnapPP/releases/tag/Fixed).

**Comment by eni9889** [comment]
Yea sadly this had to be changed sorry
