### ISSUE TITLE
Snap++ could not refresh. Please try again. 

### ISSUE THREAD

**Issue by TinoP313** [eni9889/SC-PP-ISSUES#108]
"Could not refresh. Please try again"
Version: Snapchat.v10.20.0_v1.6r-171.Duplicate.of.App.Store.App.ipa
ISO 11.1

I’ve tried everything from reinstalling, deleting the orginal app. Please help.

**Comment by uhhmaybe** [comment]
Downgrade to `Snapchat.v10.17.6_v1.6r-168.Duplicate.of.App.Store.App` and it should work.

**Comment by TinoP313** [comment]
Thanks.

**Comment by TinoP313** [comment]
How do I downgrade the app?

**Comment by uhhmaybe** [comment]
Just delete the new one and install the old one...
