### ISSUE TITLE
"Could not refresh. Please try again" 

### ISSUE THREAD

**Issue by ishmurda** [eni9889/SC-PP-ISSUES#109]
Everything works fine on Snapchat ++?i just can’t load anybody’s stories. I’ve reinstalled the app so many times and still nothing.

Version: Snapchat.v10.20.0_v1.6r-171.Duplicate.of.App.Store.App.ipa
ISO 11.1

If there’s a better version please leave link under response so I could download it thank you (:

**Comment by sololau00** [comment]
Https://Appvalley.vip
