### ISSUE TITLE
Snapchat++ “could not refresh” problem 

### ISSUE THREAD

**Issue by Bali60** [eni9889/SC-PP-ISSUES#124]
I can not load or view any stories,not even my own. Chats work fine but nothing else. Please help me ! What should I do to fix this problem, my friends use it too it worked perfectly fine for them.

**Comment by arsenopoulos** [comment]
I just figured it out, for people in the same case like me, just delete the snapchat++ version you have, open the Tutuapp delete also the sc++ you have downloaded before then download a new one just follow these steps it will work.

**Comment by Bali60** [comment]
I tried that many times, I’m not familiar to the tutuapp, can you please tell me where can I get it from ?

**Comment by arsenopoulos** [comment]
Hi, tape tutuapp.com

**Comment by arsenopoulos** [comment]
From that website you will download the snapchat++ similar application version of what you had before and that  doesnt work now

**Comment by Bali60** [comment]
Thank you so much, it did work, but a few hours after I signed in I was banned from sc and so was my friend, I don’t know if you have experienced this. If you have then can you please advice me if wether I should or should not use Snapchat ++ after my ban is lifted.

**Comment by arsenopoulos** [comment]
Hi, i have the same problem again, still ! Snapchat just locked my account. I think we should get backt to the normal app of snapchat

**Comment by Bali60** [comment]
Hi, I hope the issue gets fixed soon, the normal snapchat is boring :(
