### ISSUE TITLE
Instagram ++ (1.7r-196) , instagram (10.25) Crash issue

### ISSUE THREAD

**Issue by ghost** [eni9889/SC-PP-ISSUES#13]
IOS Version : iPhone 6s Plus (Jailbroken) on IOS (9.0.2)
Instagram : 10.25
IG ++ : 1.7r-196

Instagram keep crashing when I click on the camera button in it. everything else is fine only when I click on the Camera and this issue happened after the last update which is 10.25

**Comment by TheNightRider12** [comment]
Why is this in Snapchat++?
