### ISSUE TITLE
[Bug] Autosave snap not working

### ISSUE THREAD

**Issue by spik2012** [eni9889/SC-PP-ISSUES#140]
Autosave and selective Autosave of snaps has not worked since 10.17.6. It hasn’t worked on any later versions.

**Comment by sololau00** [comment]
It’s working maybe you just ,forget to select a locations to save you photo.

**Comment by spik2012** [comment]
On what version?

**Comment by spik2012** [comment]
Also, I'm on iOS 11.2.2, not jailbroken
