### ISSUE TITLE
Snapchat keeps saying cannot refresh and you have to log out and back in to fix it 

### ISSUE THREAD

**Issue by loughers** [eni9889/SC-PP-ISSUES#142]

**Comment by eni9889** [comment]
Which version of Snapchat and which iOS version?

**Comment by loughers** [comment]
iOS 9.3.2 and Snapchat 10.22.2 but it's been happening on previous versions aswel

**Comment by sololau00** [comment]
Where did you get snap++?

**Comment by loughers** [comment]
Cydia

**Comment by sololau00** [comment]
Official repo ? And you Snapchat it’s from AppStore?

**Comment by loughers** [comment]
The repo is 'beta.unlimapps.com' and yeah snapchat is from the AppStore

**Comment by sololau00** [comment]
You have how many friend?when you sending snap?
Or else make you phone to unjailbreak stats the resend.if work means tweak
had bug.

loughers <notifications@github.com>于Thu, 18 Jan 201811:15 PM写道：
