### ISSUE TITLE
[BUG] Autoload settings, disable shutter sound (Not working) iOS 10.1.1

### ISSUE THREAD

**Issue by Nawaf-NM** [eni9889/SC-PP-ISSUES#147]
hello :fox_face: 

All Autoload settings do not work, And also disable shutter sound not work even after it is turned on

I hope to solve the problem

iOS Version: 10.1.1 [**jailbroken**]
Snapchat Version: 10.23.6
Tweak Version: 1.7r-6

**Comment by akaBross** [comment]
I have the same problem, so I do not spam here.
