### ISSUE TITLE
[BUG] Could not refresh

### ISSUE THREAD

**Issue by dmg243** [eni9889/SC-PP-ISSUES#157]
With the new version of Snapchat, when opening the app, it says could not refresh on the top

Jailbreak
iOS: 10.2
Snapchat version: 10.24.0.0
SC ++ tweak version: 1.7r-6

**Comment by Haunter** [comment]
Second. Have tried a refresh of the Snap++ tools via the ssh commands provided with no joy, still errors out with could not refresh.

iOS:11.1.2
Snapchat version:10.24.0.0
Tweak version:Snap++ that comes down with electra commands.

**Comment by ThePlugsSon** [comment]
Snaps come in but, stories won’t refresh. Worked before I installed Electra Beta 9
———————————————————
iOS 11.1.2
Snapchat Version 10.24.5.0
Snapplus via SSH Script.

**Comment by ReMoTtt** [comment]
I was having the same problem so i downgraded Snapchat and it worked again i guess Snapchat found a way to detect jailbreakers 😂 
Just downgrade and it will go normal again and wait for coming updates for the tweak

**Comment by ThePlugsSon** [comment]
How Can I downgrade it

**Comment by ghost** [comment]
To what version? I tried multiple versions and ot still doesn't work.

**Comment by Daryan97** [comment]
I've tried multiple versions too, only way to make snapchat work is to enable jailprotect, which is a jailbreak detection protector and disable cydia for that app

**Comment by ghost** [comment]
Yes, but thats not a fix. I still want to use snap+.
