### ISSUE TITLE
[BUG] could not refresh

### ISSUE THREAD

**Issue by Daryan97** [eni9889/SC-PP-ISSUES#161]
I believe snapchat added a new jailbreak detection system for their app because when i use Jailprotect to disable jailbreak on snapchat, it works but disables this tweak. I really need this tweak so please give us an anti-jailbreak detection fix

IOS version: 10.2
Tweak version: 1.7r-6
App version: I've tried 10.23.11 to 10.24.5 (i believe even older versions not working because this is a server update not app)

**Comment by IAyazI** [comment]
I'm getting the same problem and I have to use no sub on snapchat until it gets fixed, what's taking so long!

**Comment by mrwavesurf22** [comment]
Where did you manage to download an updated version of the app? I've been looking everywhere but no luck. I'm currently on v10.19.5
