### ISSUE TITLE
LITERALLY EVERYTHING RN

### ISSUE THREAD

**Issue by JesterKing07** [eni9889/SC-PP-ISSUES#163]
Ok you guys made me have to make a whole ass profile so I can tell you guys to step it up. First of all, a while ago, I had a higher snap version than the tweak could handle and it gave me the pop up message that it couldn't take it. I forgot which one i pressed but now my Snapchat has no substrate whatsoever and it's not jailprotect or Liberty. It's your stupid tweak. Tell me how to fix this. Second of all, the current tweak version does not do anything that it is supposed to at all. And it's even worse for me because now I have no substrate in snap because of you. And also you've made all previous versions of the tweak not allow me  do anything concerning my stories or anyone else's by not refreshing. I also cant upload from camera roll like I used to be able to. Even to 1:1 streaks. This is really ridiculous and it seems like you're doing this on purpose by making the previous versions of the tweak irrelevant. Please please please fix. And stop leaving the poor people below me's problems open either. I feel like this is not coincidental and you're dumping out on us. Tell us if you are instead of doing this ruse so I can go back to Phantom if you really are cancelling this tweak

**Comment by uhhmaybe** [comment]
This is a good idea, insulting him and yelling at him will definitely get your problems addressed.  Great thinking. 

Why don't you just downgrade back to a working version until it's fixed?  Problem solved, you're welcome.

I seriously don't understand the people posting on here.  What a bunch of assholes, no wonder he takes his time fixing bugs.

**Comment by JesterKing07** [comment]
Actually that's what I did. But I still have no substrate and it's particularly annoying. I use this app everyday and to have something this breaking is nerve racking. Maybe if you had it this way you would be as angry as I am. This isn't recent either. It's been like this for a year so yea. You do that and let me hear if you get angry or not by then
