### ISSUE TITLE
[BUG] Notifications not showing

### ISSUE THREAD

**Issue by Tile124** [eni9889/SC-PP-ISSUES#168]
iOS Version: 11.2
 Snapchat Version: Snapchat++
Sideloaded

Notifications do not show up, no push notifications or anything.

**Comment by TheBigRigatoni** [comment]
Yep there is no feature in the app to adjust for it

**Comment by Floflobel** [comment]
Why no functionality to adjust this? When you install the application for the first time, you are asked if you want to receive notifications and when you accept, you have none.
