### ISSUE TITLE
Black screen on camera 

### ISSUE THREAD

**Issue by blingy5** [eni9889/SC-PP-ISSUES#180]
Snapchat version: 10.26.1.0
IOS: 10.1.1
Jailbroken 
Snapchat++: 1.7r-8 
When i downgrade to 1.7r-4 (the update to fix this black screen) the camera isnt black anymore but when i take a picture the app craches.
Every other version of sc++ just shows a black screen and cant upload photos either.
Please fix this issue thank you.

**Comment by blingy5** [comment]
The latest version of snapchat that works is 10.22.2.0

**Comment by andremouss** [comment]
I have the same issue

**Comment by heska77240** [comment]
I found the fix its work for me, install "jailprotect" on cydia and enabled it !

**Comment by heska77240** [comment]
Its working on the lastest version of Snapchat

**Comment by blingy5** [comment]
Thank you, it worked for a little bit but when you log out it starts to get really buggy and i wasnt able to take a picture without it crashing, had to go back to snapchat 10.22.2

**Comment by heska77240** [comment]
For me all is working fine on the lastest version of snapchat and tweak .....
Try to clean your phone with iCleaner......
