### ISSUE TITLE
Black camera screen

### ISSUE THREAD

**Issue by djlucklu** [eni9889/SC-PP-ISSUES#181]
Keep getting black camera on 10.26.1 - 10.23.0 and sc++ 1.7r8..  it's fixed if I downgrade to sc + 1.7r5 or 1.7r8 and snap 10.22.2.0 Only

**Comment by heska77240** [comment]
I found the fix its work for me, install "jailprotect" on cydia and enabled it

**Comment by djlucklu** [comment]
But I can't upload from my camera roll , like I use to . Let's me choose my photo , soon as I click done , it goes back to trying to record or take a pic

**Comment by djlucklu** [comment]
I updated to latest snap chat and snap +. And disabled on jailprotect.  I dontbhqve anemone installed at,all
