### ISSUE TITLE
Snapchat won't open

### ISSUE THREAD

**Issue by djlucklu** [eni9889/SC-PP-ISSUES#200]
Unable to open Snapchat. Installed snap+ 1.7r49 and nownsnap jisy instantly crash .  Tried reverting back to previous snap+ still doesn't work . Snap only works if I uninstall snap+

**Comment by heska77240** [comment]
Same issue for me !!

**Comment by heska77240** [comment]
I tried to uninstall Anemone and it working fine

**Comment by djlucklu** [comment]
I disabled the toggle on snap chat inside  jailprotect

**Comment by heska77240** [comment]
And its working for you ?? When i disable the toggle in jailprotect i have a black camera on snapchat, and i need to uninstall Anemone to fix this black camera... and you ?
