### ISSUE TITLE
Cant install snapchat + 

### ISSUE THREAD

**Issue by ZE3X** [eni9889/SC-PP-ISSUES#207]
![73efffa3-7741-42e6-83f3-c142de267b10](https://user-images.githubusercontent.com/37283612/37265870-d512d860-25cf-11e8-829b-f3a5487f5d78.png)
 When i try to install it gave this screen

**Comment by justin0386** [comment]
I also get this when trying to update it

**Comment by ZE3X** [comment]
so any solutions!!
