### ISSUE TITLE
[BUG] Snapchat++ detected?

### ISSUE THREAD

**Issue by vic197** [eni9889/SC-PP-ISSUES#212]
iOS Version 10.1.1 
 Snapchat: Newest Version
 SC ++: Newest version

Just got the message from teamsnapchat that i was using a third party app and my account was locked for 12 hours. I was not using snapchat recently. What does this mean?

**Comment by 9bguzzi** [comment]
Me too, did not location spoof or anything.

**Comment by djlucklu** [comment]
Does " can not connect message " when trying to login means I'm blocked ?

**Comment by djlucklu** [comment]
Yup I'm blocked too

**Comment by vic197** [comment]
For me, first i got a message for team snapchat that my account is locked. The next time I opened the app I was signed out and told my account was locked.

**Comment by heska77240** [comment]
Blocked too :(

**Comment by justin0386** [comment]
Same

**Comment by andremouss** [comment]
Mine did aswell, I contacted Snapchat support on twitter and they told me to wait the 12 hours

**Comment by ghost** [comment]
Experienced it too, but I'm also glad to know I'm not the only one with this problem. Got my account back 10 minutes ago

**Comment by djlucklu** [comment]
Just got mine back.  Should we downgrade snap+
