### ISSUE TITLE
New Update got account locked

### ISSUE THREAD

**Issue by Captainuae** [eni9889/SC-PP-ISSUES#213]
Please verify the new update it locks account mines got for 12 hours yet..

**Comment by andremouss** [comment]
Mine did aswell, I contacted Snapchat support on twitter and they told me to wait the 12 hours

**Comment by djlucklu** [comment]
Just got out of lock

**Comment by heska77240** [comment]
Do you know if snapchat will detect the tweak if we retry ???

**Comment by Captainuae** [comment]
i have stopped using tweak until developer fixed this issue i recommend lets wait for the developer to fix it 
other wise recent tweak is keep on tracking and locking account
