### ISSUE TITLE
[NOTICE] Please Read Before Posting Issues

### ISSUE THREAD

**Issue by eni9889** [eni9889/SC-PP-ISSUES#217]
# SC ++ Issues

***Before posting make sure you are on the latest version of SC ++ on https://beta.unlimapps.com***

Please use the issues portion of this repo to report any issues you find or for feature requests.

Bugs/Crashes should Include the following and be titled as so and also labled as a bug:

[BUG] Some title

- [ ] iOS Version
- [ ] Snapchat Version
- [ ] SC ++ Tweak Version
- [ ] Crash Report: http://tweakcrashed.com
- [ ] Please label the issue either Jailbreak or Sideloaded

Feature Requests should include the following:

[FEATURE] Some title

- [ ] Feature description
- [ ] If possible feature screenshots

Please note this repo is not for Ad Removal issues. If you are having ad removal issues please contact me at support@unlimapps.com

Any issues about account locks will be removed. There is no perfect way to "beat" DRM so there is always a risk to using third party a tweak, and you must agree to the below before you can use the tweak.

![alt text](https://github.com/eni9889/SC-PP-ISSUES/raw/master/IMG_0511.jpg)

**Comment by uhhmaybe** [comment]
You should make an Github Issue template that fills in the box when users create a new Issue so they're forced to read the disclaimers and input the relevant info.
