### ISSUE TITLE
[BUG] Locked out

### ISSUE THREAD

**Issue by TheAlfkid** [eni9889/SC-PP-ISSUES#23]
iOS 10.2.1 (14D27)
Snapchat++ v10.10.2_1-6r-155 (sideloaded)
![snap](https://user-images.githubusercontent.com/19878012/27492189-97f0b0b8-5845-11e7-99d0-4d98188e454b.jpg)
Can't really put crash report in since that isn't the problem here.

**Comment by TheAlfkid** [comment]
Also I don't receive notifications for the app even though it's on and I've tried reinstalling it and it just won't work.

**Comment by eni9889** [comment]
Please note that using 3rd party tweaks and apps is against Snapchat TOS and it could get your account locked / banned. This tweak does not implement any kind of DRM checks nor is it possible to know every method that Snapchat could use to detect its presence. Use at your own risk.
