### ISSUE TITLE
Viewing Snapchat stories

### ISSUE THREAD

**Issue by ghost** [eni9889/SC-PP-ISSUES#32]
I cannot next a story as fast as I can without snap+ installed....it is very laggy when I go to the next story

**Comment by thenewi8** [comment]
Hi,
Verify your settings in Snap + settings and update to the latest version.
If the issues is gone please close this 👍

**Comment by ghost** [comment]
It's the latest version still laggy

**Comment by thenewi8** [comment]
Works fine on the lastest version. Try to reinstall the app.
Warmly

**Comment by ghost** [comment]
Pressing the eye isn't the Bottom corner works fine no lag but when I press
the right of the screen for next story it is super laggy
