### ISSUE TITLE
[BUG] Video uploading sending problem

### ISSUE THREAD

**Issue by emojifather** [eni9889/SC-PP-ISSUES#36]
iOS Version: 10.3.1
 Snapchat Version: v10.13.0
 SC ++ Tweak Version: 1.6r-136
 Crash Report: N/A
 App is Sideloaded

Whenever I upload a video from  my camera roll, it does not let me press the blue send button in the bottom right corner once the video is uploaded.

**Comment by eni9889** [comment]
Please update the tweak this issue should be fixed
