### ISSUE TITLE
[FEATURE] Selective Story Watching

### ISSUE THREAD

**Issue by ghost** [eni9889/SC-PP-ISSUES#37]
Hi I have a feature request. When you click the stories button to select all stories to watch, there should be an option to only watch stories you pre-selected that you frequently watch. Instead of watching A,B,C, and D, I selected beforehand that I only wanna see B and D, so then when I click the stories button, A and C won't be selected

I know this is similar to the mute feature but due to having 2000+ friends on snapchat and muting 75%+ of them, when I try to add/remove people from the list my app crashed and when I enable the mute feature my app freezes.

**Comment by eni9889** [comment]
Can you please provide a crash report following instructions at http://tweakcrashed.com
