### ISSUE TITLE
[BUG] Mark as read not working properly

### ISSUE THREAD

**Issue by casualsailo** [eni9889/SC-PP-ISSUES#4]
iOS Version: 9.3.3
Facebook Version: 10.7.2
Tweak Version: 1.6r-98

When viewing an individual snap, tapping the mark as read (the eye looking icon on bottom left) closes the snap as expected

However, the snap's status is still shown as unread when on the convo screen. Tapping the snap does nothing. To update the convo screen, you must go to the home screen and then reopen snapchat

It seems that Snaps Settings -> Unlimited Snaps views doesn't do anything

Marking group snaps as read closes the snap and updates the convo screen to read as expected

**Comment by eni9889** [comment]
So this is only for viewing of individual snaps?

**Comment by casualsailo** [comment]
Yes, seems to only be a problem on individual snaps

**Comment by dyarfaradj** [comment]
Eni, when you get a snap you will have to press the read button and then it will just show up as a unseen snap, then you refresh the snaps and then the snap will be read.

**Comment by uhhmaybe** [comment]
I have this problem as well.  You click the eye icon and the snap is now "read", but the UI doesn't reflect that.  It's not until you refresh the Chat page that the unread icon will change to read.  It's not a major problem, but it's kind of confusing at first until you realize what's happening.

iOS: 10.2
App Store Snapchat Version: 10.8.1
Tweak Version: Snapchat++ v10.8.0_1.6r-103 Duplicate.ipa
Type: Sideloaded

**Comment by uhhmaybe** [comment]
This seems to be resolved in v10.8.0_1.6r-104, though I haven't tested it too thoroughly.

**Comment by TheNightRider12** [comment]
Marking this as resolved.
