### ISSUE TITLE
Snapchat+

### ISSUE THREAD

**Issue by tooky1986** [eni9889/SC-PP-ISSUES#53]
It keep saying could not refresh please try again later

**Comment by eni9889** [comment]
Which  version of Snapchat?

**Comment by tooky1986** [comment]
10.16.1 I downloaded from tutu

**Comment by tooky1986** [comment]
10.16.1 I got it from tutu

**Comment by uhhmaybe** [comment]
Same here.  I posted my info in https://github.com/eni9889/SC-PP-ISSUES/issues/54.

**Comment by sololau00** [comment]
Use "Appvalley" Google It then Install.
