### ISSUE TITLE
Snapchat plus and phantom Snapchat 

### ISSUE THREAD

**Issue by quansimmons** [eni9889/SC-PP-ISSUES#58]
Keep crashing when trying save a snap keep getting could refresh try again no internet connection

**Comment by eni9889** [comment]
Which version do you have installed?

**Comment by quansimmons** [comment]
10.15

**Comment by eni9889** [comment]
You need to update  to latest version

**Comment by quansimmons** [comment]
Where can I find it do it have to be on a computer because I don't have one

**Comment by eni9889** [comment]
I cannot distribute IPAs but you can try https://github.com/JMccormick264/PPAppsIPARepo

**Comment by quansimmons** [comment]
Well is it just for me to do on a computer because when I click the link it
just download a file to my phone without doing anything
