### ISSUE TITLE
[Feature request ] sc++spoof location

### ISSUE THREAD

**Issue by sololau00** [eni9889/SC-PP-ISSUES#65]
Feature description :
You can try to copy "SCOthman for snapchat" spoof location it cover all the world. TQ.or self adding spoof location :)

**Comment by TheNightRider12** [comment]
Spoofing your location can lead to bans and locked accounts.

**Comment by sololau00** [comment]
If using "SCOthman for snapchat" spoofing location also lead to ban or lock?
