### ISSUE TITLE
Uploaded Image Quality

### ISSUE THREAD

**Issue by tomperson349** [eni9889/SC-PP-ISSUES#68]
Whenever I upload image from camera roll and send as real time snap the image quality is far worse. Its noticably different from the actual quality of the uploaded image.

**Comment by jaydee32526** [comment]
This is differently an issue I thought it was my phone for a while

**Comment by tomperson349** [comment]
I actually switched to IOS 10 on different device. No longer have this issue. Seems to be only with IOS 9
