### ISSUE TITLE
Snapchat+++ (Emoji/Sticker Issue)

### ISSUE THREAD

**Issue by diplodropit** [eni9889/SC-PP-ISSUES#70]
iOS Version : iOS 11.0
Snapchat Version : 10.17.5
SC ++ Tweak Version:10.9-4
Device : Not Jailbreak
Issue : every time I try to put a sticker/emoji on a photo or video from my camera roll it completely freezes the app and I have to turn my phone on and off again.

**Comment by jaydee32526** [comment]
I have this issue sometimes as well
