### ISSUE TITLE
[Bug]Sc++ Could not refresh

### ISSUE THREAD

**Issue by sololau00** [eni9889/SC-PP-ISSUES#73]
iOS Version : ios 9.3.5
 Snapchat Version:10.18.0
 SC ++ Tweak Version : 1.6r-169
 Jailbreak 
It sometimes could not refresh.

**Comment by Aenar** [comment]
This "could not refresh" issue is becoming ridiculous; I've been able to view stories maybe three times in the past week, sometimes it works for 5 minutes, sometimes an hour or two, but mostly this error has become intolerable and is causing me to want to use a different tweak.   Please address this issue!

___________________________
SC++ Version: 1.6r-169
uasharedtools:  2.1r-113
SC Version: 10.18.1.0
iOS: 9.0.2

**Comment by sololau00** [comment]
Try use "SCOthman For Snapchat" More Spoof Location

**Comment by sololau00** [comment]
It's fixed?
