### ISSUE TITLE
snapchat crashes a few seconds after launch

### ISSUE THREAD

**Issue by bartkramer** [eni9889/SC-PP-ISSUES#80]
Sideloaded snapchat ++ crashes after being open for around 5 seconds. iPhone 8+ 11.0.2. Downloaded ipa from appdb.

**Comment by sololau00** [comment]
just Use this "https://appvalley.vip/"  Don't use other Site.

**Comment by bartkramer** [comment]
Does appvalley include notifications?

**Comment by sololau00** [comment]
i don't know but it woerk for non jailbreak

**Comment by sololau00** [comment]
No,the developer still traveling just wait him come back to fix it😂
