### ISSUE TITLE
Can't connect with 10.19.0

### ISSUE THREAD

**Issue by elmagow** [eni9889/SC-PP-ISSUES#81]
When I try to connect to my snapchat account, it tells me "No internet connection, cannot connect"

i7, ios10.3.1

**Comment by lisanaryia** [comment]
Hey man, can you please tell me where you got the Snapchat++ 10.19.0, They only have the 10.18.0 on the appvaley and the tutuapp

**Comment by lisanaryia** [comment]
Same problem here

**Comment by sololau00** [comment]
Have You try "https://appvalley.vip/"?
