### ISSUE TITLE
Snap feed doesn't load at all

### ISSUE THREAD

**Issue by DjSupremeTheGreat** [eni9889/SC-PP-ISSUES#86]
Also I can't add new friends via snap code

**Comment by eni9889** [comment]
Which tweak version and Snapchat version?

**Comment by DjSupremeTheGreat** [comment]
10.19.0 Snap++

          

Best,
Aldreaon Smith
 
"Do not go where the path may lead,
go instead where there is no path and
leave a trail." - Ralph Waldo Emerson
