### ISSUE TITLE
[MAJOR BUG] Snapchat++ LATEST VERSION

### ISSUE THREAD

**Issue by oeieifidiidid** [eni9889/SC-PP-ISSUES#88]
Hi, 

When I select a video from my Camera Roll to send to my friends and/or SnapStory, the video opens as it should and allows me to trim/crop the video if I need to. Once I’m down trimming the video, I click “Choose” and this is where the issue begins. 

When I click “Choose” it goes to the next screen (where I can add a caption, filter, etc.), but only a still image is seen and the video sort of vanishes. I’m not sure if the recipient actually gets the video or a still image from the video, but nonetheless, sending a video takes extremely long. The previous version had no issues, so I just downgraded. I also noticed when I send a video to someone, in the chat, it shows “Delivered”, but the colour is red, when it should be purple since it’s a video. 

There’s a few bugs with the latest version of Snapchat++ that can be found on the Download Links page. I’m on iOS 11.1. iPhone 6s Plus. Please fix this issue so that I can upgrade to latest version.

**Comment by eni9889** [comment]
Which version of the tweak do you have installed and which version of Snapchat?

**Comment by oeieifidiidid** [comment]
I have the latest version available installed and sorry, what do you mean which version of Snapchat? I only have the ++ version, which is yours.

**Comment by oeieifidiidid** [comment]
Snapchat Version 10.19.5.0

**Comment by oeieifidiidid** [comment]
Sorry, not Snapchat Version, meant to say Tweak Version.

**Comment by oeieifidiidid** [comment]
Tweak version: 10.19.5.0

Only have the ++ tweak installed

**Comment by oeieifidiidid** [comment]
I guess you could say I have the latest Snapchat version?

**Comment by oeieifidiidid** [comment]
I was going to screen record my issue, but I’ve already downgraded to an older version of your tweak, since I’m this version video works. The only issue with this one is that the recipient doesn’t actually get a video, just a still image which is weird. The colour on the “Delivered” is also red, so indeed they’re not getting a video, even though I sent a video.
