### ISSUE TITLE
[Feature Request] dunno if this is possible, but make it so that when Snapchat turns on their tweak detection again, we will still be able to use Snap +

### ISSUE THREAD

**Issue by ghost** [eni9889/SC-PP-ISSUES#9]
Tweaks like Phantom Lite has jailbreak detection bypassing, but there's not much features on it unlike Snap +.  Could you make it so Snap+ won't be detected by Snapchat again when they turn on Jailbreak detectors

**Comment by TheNightRider12** [comment]
He will not be doing this due to him having a full time job. And fighting DRM would take too much time. Check Unlim's twitter.

**Comment by ghost** [comment]
I see.  I hope he finds time to work on this one day.
